vich_uploader:
    db_driver: orm

    mappings:
        standby_media:
            uri_prefix: /media/standby
            upload_destination: '%kernel.project_dir%/public/media/standby'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
